### ISSUE TITLE
How to reload <script src="..."> ?

### ISSUE THREAD

**Issue by Juuly** [brcontainer/pjax.js#1]

**Comment by brcontainer** [comment]
@Juuly Sorry, I did not understand.

**Comment by brcontainer** [comment]
@Juuly Is your `<script src="...">`  in the <head></head>?

**Comment by Juuly** [comment]
how to say) restart some script on page. Example: alert('test') should work each reload page

**Comment by brcontainer** [comment]
@Juuly Try events: https://github.com/brcontainer/pjax.js#pjax-events

**Comment by Juuly** [comment]
Tried. 'Uncaught ReferenceError: callbacks is not defined'

**Comment by brcontainer** [comment]
@Juuly This error was in the last update
I will correct it, as soon as possible I will send the commit.

**Comment by Juuly** [comment]
Ok, thanks

**Comment by brcontainer** [comment]
@Juuly fixed in https://github.com/brcontainer/pjax.js/commit/08396dfaa1229c6e816e4ea18b7f747005032c44
